export const classes = [
  {
    "id": 1,
    "mask": 1,
    "powerType": "rage",
    "name": "Warrior"
  }, {
    "id": 2,
    "mask": 2,
    "powerType": "mana",
    "name": "Paladin"
  }, {
    "id": 3,
    "mask": 4,
    "powerType": "focus",
    "name": "Hunter"
  }, {
    "id": 4,
    "mask": 8,
    "powerType": "energy",
    "name": "Rogue"
  }, {
    "id": 5,
    "mask": 16,
    "powerType": "mana",
    "name": "Priest"
  }, {
    "id": 6,
    "mask": 32,
    "powerType": "runic-power",
    "name": "Death Knight"
  }, {
    "id": 7,
    "mask": 64,
    "powerType": "mana",
    "name": "Shaman"
  }, {
    "id": 8,
    "mask": 128,
    "powerType": "mana",
    "name": "Mage"
  }, {
    "id": 9,
    "mask": 256,
    "powerType": "mana",
    "name": "Warlock"
  }, {
    "id": 10,
    "mask": 512,
    "powerType": "energy",
    "name": "Monk"
  }, {
    "id": 11,
    "mask": 1024,
    "powerType": "mana",
    "name": "Druid"
  }, {
    "id": 12,
    "mask": 2048,
    "powerType": "fury",
    "name": "Demon Hunter"
  }
]

export const races = [
  {
    "id": 1,
    "mask": 1,
    "side": "alliance",
    "name": "Human"
  }, {
    "id": 2,
    "mask": 2,
    "side": "horde",
    "name": "Orc"
  }, {
    "id": 3,
    "mask": 4,
    "side": "alliance",
    "name": "Dwarf"
  }, {
    "id": 4,
    "mask": 8,
    "side": "alliance",
    "name": "Night Elf"
  }, {
    "id": 5,
    "mask": 16,
    "side": "horde",
    "name": "Undead"
  }, {
    "id": 6,
    "mask": 32,
    "side": "horde",
    "name": "Tauren"
  }, {
    "id": 7,
    "mask": 64,
    "side": "alliance",
    "name": "Gnome"
  }, {
    "id": 8,
    "mask": 128,
    "side": "horde",
    "name": "Troll"
  }, {
    "id": 9,
    "mask": 256,
    "side": "horde",
    "name": "Goblin"
  }, {
    "id": 10,
    "mask": 512,
    "side": "horde",
    "name": "Blood Elf"
  }, {
    "id": 11,
    "mask": 1024,
    "side": "alliance",
    "name": "Draenei"
  }, {
    "id": 22,
    "mask": 2097152,
    "side": "alliance",
    "name": "Worgen"
  }, {
    "id": 24,
    "mask": 8388608,
    "side": "neutral",
    "name": "Pandaren"
  }, {
    "id": 25,
    "mask": 16777216,
    "side": "alliance",
    "name": "Pandaren"
  }, {
    "id": 26,
    "mask": 33554432,
    "side": "horde",
    "name": "Pandaren"
  }
]
